"use client";
import {FormEvent,useEffect,useState} from "react";
type Item={id:number;recordType:string;recordId:string;summary:string;sourceUrl:string;sourceNote:string;spoilerClass:string;status:string;authorEmail:string;editorNote:string};
type RecordRow={id:number;recordType:string;recordId:string;title:string;status:string;updatedAt:string};
type Citation={id:number;recordType:string;recordId:string;label:string;url:string;sourceKind:string};
type Revision={id:number;recordType:string;recordId:string;version:number;summary:string;contributor:string};
type Research={id:number;officerId:string;authorEmail:string;biography:string;gameplay:string;weapon:string;battles:string;relationships:string;unlockCondition:string;spoilerNotes:string;sourceUrl:string;sourceNote:string;approvedFields:string;status:string;editorNote:string};
type Payload={contributions:Item[];records:RecordRow[];citations:Citation[];revisions:Revision[];research:Research[]};

export default function EditorClient(){
  const[data,setData]=useState<Payload>({contributions:[],records:[],citations:[],revisions:[],research:[]});const[error,setError]=useState("");const[notice,setNotice]=useState("");const[tab,setTab]=useState("research");const[selected,setSelected]=useState<Record<number,string[]>>({});
  function load(){fetch("/api/editor").then(async r=>{const j=await r.json();if(!r.ok)setError(j.error);else{setData(j);setError("")}})}
  useEffect(load,[]);
  async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();setNotice("Saving…");const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());const r=await fetch("/api/editor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,action})});const j=await r.json();if(!r.ok)setNotice(j.error);else{setNotice("Saved to the archive.");e.currentTarget.reset();load()}}
  async function review(id:number,status:string,note:string){await fetch("/api/editor",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,editorNote:note})});load()}
  function toggleField(id:number,field:string){const current=selected[id]||[];setSelected({...selected,[id]:current.includes(field)?current.filter(x=>x!==field):[...current,field]})}
  async function reviewResearch(id:number,status:string){setNotice("Saving editorial decision…");const note=(document.getElementById(`research-note-${id}`) as HTMLTextAreaElement)?.value||"";const r=await fetch("/api/editor",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status,editorNote:note,kind:"structured",approvedFields:selected[id]||[]})});const j=await r.json();setNotice(r.ok?"Editorial decision saved.":j.error||"Could not save.");load()}
  if(error)return <div className="community-empty"><h2>{error}</h2><p>Your profile must carry the editor or admin role before this workspace becomes available.</p></div>;
  return <div className="editor-workspace">
    <nav className="editor-tabs" aria-label="Editorial tools">{[["research","Profile research"],["records","Records"],["sources","Sources"],["revisions","Revisions"],["queue","Corrections"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>{setTab(id);setNotice("")}} key={id}>{label}<span>{id==="research"?data.research.length:id==="records"?data.records.length:id==="sources"?data.citations.length:id==="revisions"?data.revisions.length:data.contributions.length}</span></button>)}</nav>
    {notice&&<p className="editor-notice" role="status">{notice}</p>}
    {tab==="research"&&<div className="research-review">{data.research.length?data.research.map(x=>{const fields=[["biography","Biography",x.biography],["gameplay","Gameplay",x.gameplay],["weapon","Weapon",x.weapon],["battles","Battles",JSON.parse(x.battles).join(", ")],["relationships","Relationships",JSON.parse(x.relationships).join(" · ")],["unlockCondition","Unlock",x.unlockCondition],["spoilerNotes","Spoilers",x.spoilerNotes]];return <article key={x.id}><header><div><span className={`status-pill ${x.status}`}>{x.status}</span><h2>{x.officerId}</h2><small>{x.authorEmail}</small></div><a href={x.sourceUrl} target="_blank" rel="noreferrer">Inspect source ↗</a></header><p className="source-note">{x.sourceNote||"No verification note supplied."}</p><div className="field-review">{fields.map(([id,label,value])=><label className={selected[x.id]?.includes(id)?"approved":""} key={id}><input type="checkbox" checked={selected[x.id]?.includes(id)||false} onChange={()=>toggleField(x.id,id)}/><span><strong>{label}</strong><p>{value||"No content submitted."}</p></span></label>)}</div><label className="review-note">Editorial note<textarea id={`research-note-${x.id}`} defaultValue={x.editorNote}/></label><div className="review-actions"><button onClick={()=>reviewResearch(x.id,"approved")} disabled={!selected[x.id]?.length}>Publish selected fields</button><button onClick={()=>reviewResearch(x.id,"needs-changes")}>Request changes</button><button onClick={()=>reviewResearch(x.id,"declined")}>Decline</button></div></article>}):<div className="community-empty"><h2>No claimed research is awaiting review.</h2><p>Structured profile submissions will appear here field by field.</p></div>}</div>}
    {tab==="records"&&<div className="editor-columns"><form className="editor-form" onSubmit={e=>submit(e,"record")}><p className="eyebrow"><span/>NEW ARCHIVE RECORD</p><h2>Create a canonical record</h2><div className="form-pair"><label>Record type<select name="recordType"><option value="officer">Officer</option><option value="game">Game / edition</option><option value="battle">Battle</option><option value="weapon">Weapon</option></select></label><label>Stable ID<input name="recordId" placeholder="fa-zheng"/></label></div><label>Title<input name="title" required placeholder="Fa Zheng"/></label><label>Summary<textarea name="summary" required placeholder="Spoiler-safe public summary"/></label><label>Editorial body<textarea name="body" placeholder="Long-form notes, relationships, and context"/></label><div className="form-pair"><label>Faction<input name="faction" placeholder="SHU"/></label><label>Spoiler class<select name="spoilerClass"><option value="safe">Spoiler-safe</option><option value="minor">Minor</option><option value="major">Major</option></select></label></div><button>Save draft record</button></form><section className="editor-ledger"><h2>Database records</h2>{data.records.length?data.records.map(x=><article key={x.id}><span className={`status-pill ${x.status}`}>{x.status}</span><div><strong>{x.title}</strong><small>{x.recordType} · {x.recordId}</small></div></article>):<p>No database-authored records yet. The DW8XL seed catalog is available publicly; use this form for new and expanded records.</p>}</section></div>}
    {tab==="sources"&&<div className="editor-columns"><form className="editor-form" onSubmit={e=>submit(e,"citation")}><p className="eyebrow"><span/>PROVENANCE</p><h2>Attach a source</h2><div className="form-pair"><label>Record type<select name="recordType"><option>officer</option><option>game</option><option>battle</option><option>weapon</option></select></label><label>Record ID<input name="recordId" required placeholder="dw8xl"/></label></div><label>Source label<input name="label" required placeholder="Official DW8XL game outline"/></label><label>Source URL<input name="url" type="url" required placeholder="https://…"/></label><label>Source kind<select name="sourceKind"><option value="official">Official publisher</option><option value="primary">Primary source</option><option value="reference">Reference work</option><option value="community">Community research</option></select></label><button>Add verified citation</button></form><section className="editor-ledger"><h2>Source ledger</h2>{data.citations.map(x=><article key={x.id}><span className="source-kind">{x.sourceKind}</span><div><a href={x.url} target="_blank" rel="noreferrer">{x.label} ↗</a><small>{x.recordType} · {x.recordId}</small></div></article>)}</section></div>}
    {tab==="revisions"&&<div className="editor-columns"><form className="editor-form" onSubmit={e=>submit(e,"revision")}><p className="eyebrow"><span/>CHANGELOG</p><h2>Log a revision</h2><div className="form-pair"><label>Record type<select name="recordType"><option>officer</option><option>game</option><option>battle</option><option>weapon</option></select></label><label>Record ID<input name="recordId" required placeholder="dw8xl"/></label></div><label>What changed?<textarea name="summary" required placeholder="Added official roster citation and normalized edition platforms."/></label><button>Publish revision note</button></form><section className="editor-ledger"><h2>Revision history</h2>{data.revisions.map(x=><article key={x.id}><span className="revision-number">v{x.version}</span><div><strong>{x.summary}</strong><small>{x.recordType} · {x.recordId} · {x.contributor}</small></div></article>)}</section></div>}
    {tab==="queue"&&<div className="editor-queue">{data.contributions.length?data.contributions.map(x=><article key={x.id}><header><span className={`status-pill ${x.status}`}>{x.status}</span><strong>{x.recordType} · {x.recordId}</strong><small>{x.authorEmail}</small></header><p>{x.summary}</p><a href={x.sourceUrl} target="_blank" rel="noreferrer">Inspect source ↗</a><blockquote>{x.sourceNote||"No source note supplied."}</blockquote><label>Editorial note<textarea defaultValue={x.editorNote} id={`note-${x.id}`}/></label><div><button onClick={()=>review(x.id,"approved",(document.getElementById(`note-${x.id}`) as HTMLTextAreaElement).value)}>Approve</button><button onClick={()=>review(x.id,"needs-changes",(document.getElementById(`note-${x.id}`) as HTMLTextAreaElement).value)}>Request changes</button><button onClick={()=>review(x.id,"declined",(document.getElementById(`note-${x.id}`) as HTMLTextAreaElement).value)}>Decline</button></div></article>):<div className="community-empty"><h2>The queue is clear</h2><p>New community submissions will appear here for source and spoiler review.</p></div>}</div>}
  </div>
}
