import {notFound,permanentRedirect} from "next/navigation";
import {Footer,Header} from "../../components";
import {weapons,officerById,battles} from "../../data";
import {weaponGuides,dossiers,edition,checked,manual,exSource,fusionSource,combatSource,sixthSource} from "../../archive/dw8xl";
import {SourceLinks} from "../../archive/source-links";
export default async function WeaponPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;if(id==="flame-blade")permanentRedirect("/weapons/sword");const weapon=weapons.find(w=>w.id===id);if(!weapon)notFound();
 const guide=weaponGuides.find(w=>w.id===id);const officerId=guide?.officerId??weapon.wielders.find(id=>dossiers[id]?.weaponId===weapon.id);const dossier=officerId?dossiers[officerId]:undefined;
 return <main><Header active="weapons"/><section className="archive-hero"><p className="eyebrow">WEAPON RECORD</p><h1>{weapon.name}</h1><p>{dossier?edition:"Archive seed · edition research pending"}</p></section><section className="detail-body"><div className="detail-main">
 <p><a href="/weapons">← All weapons</a></p><h2>Signature wielders</h2><div className="link-list">{weapon.wielders.map(id=><a key={id} href={`/officers/${id}`}>{officerById(id)?.name} →</a>)}</div>
 {dossier?<>{dossier.gameplay&&<><h2>Using this weapon</h2><p>{dossier.gameplay}</p>{dossier.gameplayContext&&<p>{dossier.gameplayContext}</p>}</>}<h2>EX attacks</h2><p>{dossier.exNote}</p><p>DW8XL adds a second EX attack to each officer. Both require that officer’s favorite weapon. The in-game move list is the reference for exact inputs.</p><p><strong>Notation:</strong> C1 is Strong Attack alone; C4 is three Normal Attacks followed by Strong Attack. “EX” means the officer-specific follow-up.</p><h2>Compatibility</h2><p>Other officers can equip this weapon type, but its signature officer’s EX attacks do not transfer with it. Weapon compatibility and Heaven/Earth/Man affinity are separate systems. Carrying different affinities gives you a switching option against an unfavorable matchup.</p>
 {guide&&<><details className="spoiler-panel" id="rare-weapon"><summary>Reveal {guide.rare.rank}-star weapon guide</summary><h2>{guide.rare.name}</h2><dl className="fact-grid"><div><dt>Required officer</dt><dd><a href={`/officers/${guide.officerId}`}>{officerById(guide.officerId)?.name}</a></dd></div><div><dt>Battle</dt><dd><a href={`/battles/${guide.rare.stageId}`}>{battles.find(b=>b.id===guide.rare.stageId)?.name}</a></dd></div><div><dt>Side / mode</dt><dd>{guide.rare.side}</dd></div><div><dt>Difficulty</dt><dd>Hard, Chaos or Ultimate</dd></div></dl><ol><li>Select the required officer and exact stage variant.</li><li>{guide.rare.condition}</li><li>Look for the treasure notification, collect the weapon at its marked location, then finish the battle.</li></ol><SourceLinks sources={[guide.rare.source,sixthSource]}/></details>
 <h2>Acquisition and upgrades</h2><p>The rare reward above is a particular weapon, not a requirement to start using this weapon type. Xtreme Legends also adds rare weapons and gem-based fusion. Fusion can transfer attributes, raise attack or change affinity through Ambition Mode’s Blacksmith or Free Mode’s Weapon Options.</p></>}
 <h2>Research still open</h2><p>Complete EX input tables, compatibility stars by level and weapon-rank lists still need verification. {guide?"The rare condition above is source-checked, not replay-tested.":"Rare weapon acquisition conditions have not yet been added to this record."}</p></>:<p>This seed lists a weapon association. An edition-specific moveset and acquisition guide has not yet been researched.</p>}
 </div><aside className="provenance"><h2>Sources</h2><p>Checked {dossier?.checked??checked}. Community observations are identified separately from publisher documentation.</p>{dossier&&<SourceLinks sources={[manual,exSource,...(dossier.gameplay?[combatSource]:[]),...(guide?[fusionSource,guide.rare.source]:[]),...(dossier.sources??[])]}/>}<a href={`/contribute?recordType=weapon&recordId=${id}`}>Suggest a correction →</a></aside></section><Footer/></main>
}
