"use client";
import {useMemo,useState} from "react";
import {Footer,Header} from "../components";
import {games} from "../data";
import type {ArchiveOfficer} from "../lib/archive";

export default function Officers({officers,unavailable}:{officers:ArchiveOfficer[];unavailable:boolean}){
  const[query,setQuery]=useState("");const[faction,setFaction]=useState("ALL");const[game,setGame]=useState("ALL");const[weapon,setWeapon]=useState("ALL");const[status,setStatus]=useState("ALL");
  const weapons=[...new Set(officers.map(o=>o.weapon))].sort();
  const visible=useMemo(()=>officers.filter(o=>{const kingdom=o.kingdom;return(faction==="ALL"||kingdom===faction)&&(game==="ALL"||o.games.includes(game))&&(weapon==="ALL"||o.weapon===weapon)&&(status==="ALL"||o.sourceStatus===status||(status==="published"&&o.publishedFields>0))&&(o.searchText.toLowerCase().includes(query.toLowerCase()))}),[officers,query,faction,game,weapon,status]);
  return <main><Header active="officers"/><section className="archive-hero"><p className="eyebrow"><span/>OFFICER ARCHIVE</p><h1>Warriors of the chronicle</h1><p>Compare officers across kingdoms, games, weapons, playstyles, and editorial coverage.</p></section><section className="archive-body">
    {unavailable&&<p role="status">Community updates are temporarily unavailable. Showing archive seed records.</p>}<div className="search-row"><label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search officers" placeholder="Search officers, weapons, playstyles…"/></label><a className="primary-action" href="/coverage">View coverage</a></div>
    <div className="archive-filterbar"><label>Kingdom<select value={faction} onChange={e=>setFaction(e.target.value)}>{["ALL","SHU","WEI","WU","JIN","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><label>Game<select value={game} onChange={e=>setGame(e.target.value)}><option>ALL</option>{games.map(g=><option value={g.id} key={g.id}>{g.short}</option>)}</select></label><label>Weapon<select value={weapon} onChange={e=>setWeapon(e.target.value)}><option>ALL</option>{weapons.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>ALL</option><option value="reviewed">Reviewed</option><option value="draft">Draft</option><option value="published">Published research</option></select></label><button onClick={()=>{setQuery("");setFaction("ALL");setGame("ALL");setWeapon("ALL");setStatus("ALL")}}>Reset</button></div>
    <div className="result-meta"><span>{visible.length.toString().padStart(2,"0")} OFFICERS</span><span>DW8XL CE · EDITION-SPECIFIC RESEARCH</span></div>{visible.length===0&&<p role="status">No officers match these filters. Try another search or reset the filters.</p>}<div className="officer-grid">{visible.map(o=><article className={`officer-card ${o.style}`} key={o.id}><div className="portrait"><span className="portrait-mark">{o.mark}</span><div className="silhouette"><i/><b/></div><small>{o.kingdom}</small></div><div className="card-body"><p>{o.title}</p><h3><a href={`/officers/${o.id}`}>{o.name}</a></h3><small>{o.alias}</small><p className="summary">{o.summary}</p>{o.publishedFields>0&&<small>{o.publishedFields} published research fields</small>}<div className="tags">{o.tags.map(t=><span key={t}>{t}</span>)}</div><div className="card-footer"><span>{o.weapon}</span><a href={`/officers/${o.id}`}>Open record →</a></div></div></article>)}</div></section><Footer/></main>
}
